# Generated by Django 5.2.17 on 2026-09-30 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('bloco', models.CharField(max_length=60)),
                ('capacidade', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('inscricoes_abertas', models.BooleanField(default=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('PA', 'Palestra'), ('TR', 'Treinamento'), ('AP', 'Apresentação')], max_length=2)),
                ('descricao', models.TextField(blank=True)),
                ('responsavel', models.CharField(max_length=100)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='inscricoes.evento')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades', to='inscricoes.sala')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='inscricoes.evento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_em_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrição em evento',
                'verbose_name_plural': 'Inscrições em eventos',
                'unique_together': {('evento', 'participante')},
            },
        ),
        migrations.CreateModel(
            name='InscricaoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='inscricoes.atividade')),
                ('inscricao_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_atividades', to='inscricoes.inscricaoevento')),
            ],
            options={
                'verbose_name': 'Inscrição em atividade',
                'verbose_name_plural': 'Inscrições em atividades',
                'unique_together': {('inscricao_evento', 'atividade')},
            },
        ),
    ]
